project:
  type: website

website:
  title: "Tamil Arasan"
  description: "Theoretical Physicist turned Machine Learning Research Engineer"
  # site-url: https://tamilarasan.github.io
  navbar:
    left:
      - text: "{{< fa address-card >}} Blogs"
        file: blogs/blogs.qmd
      - text: "{{< fa pen >}} Notes"
        file: notes/notes.qmd
      - text: "{{< fa flask >}} Publications"
        file: publications/publications.qmd

    right:
      # - text: "@Opensource"
        # icon: twitter
       # href: https://twitter.com/Opensource
      - icon: github
        href: https://github.com/tamil-phy
      - icon: medium
       # href: https://medium.com/@Opensource
      - icon: linkedin
        href: https://www.linkedin.com/in/tamil-arasan-644a3763/
      - icon : google scholar
        href : https://scholar.google.com/citations?hl=en&user=Szi3WqkAAAAJ&sortby=pubdate&view_op=list_works&gmla=AJsN-F5FF6TXWzNo5owa4MN9d1TvIAkPuBttSEj3rfi5MrnyFQH2-qtyV4Bs6REHAQxTxqu5V267WmpeqjxW-SSeBQmL94C9Ccd9QOEbRFVkOeB3eZbUpRw
    pinned: false

  # favicon: images/favicon.ico
  twitter-card: true
  open-graph: true
  page-footer: "{{< fa regular copyright >}} Copyright 2023, Opensource" 

  sidebar:
    

    - id: notes
      title: "Notes"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "🗣️ **Large language models**"
         # contents: "notes/Large Language Models/*"
        - text: "---"
        - section: "💡 **Machine learning**"
         # contents: "notes/Machine Learning/*"
format:
  html:
    page-layout: article
    theme: [minty, styles.scss]
    toc: true
    toc-depth: 2
    toc-title: "**Sections**"
    css: styles.css
    html-math-method: katex
    code-overflow: wrap
    highlight-style: github-dark
    code-block-background: true
    link-external-newwindow: true
    embed-resources: true

comments:
  utterances:
    repo: https://github.com/Opensource/blog