---
title: "Tamil Arasan"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: true
---
# About


Hi there, I'm **Tamil Arasan**, your bridge between Theoretical Physics and Machine Learning! Based in Chennai, but with  roots in picturesque Puducherry, I bring over seven years of research  and four years of industry expertise to the table. I believe in the  transformative power of applying machine learning techniques to complex  problems in physics. My research doesn't reside solely in the  theoretical realm; it's an actionable toolkit designed to solve  real-world challenges. Whether it's decoding the intricacies of Quantum Many-Body systems or streamlining the efficiency of Clinical Trials  through machine learning, my work aims to bridge scientific inquiry and  practical application, driving tangible advancements in both academia  and industry.

When I am not in the lab or coding, you can find me in the classroom. I'm incredibly passionate about imparting knowledge  and igniting curiosity about Physics and Mathematics in students. I love making complex concepts relatable through real-life examples, helping  students see the wonder and applicability of Physics in everyday life.

Intrigued by the entanglement of Physics and Machine Learning? Got burning  questions or novel ideas? Reach out and let's make science happen!

